name: Mutation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage --file pom.xml
      - name: Upload Pitest Report
        uses: actions/upload-artifact@v2
        with:
          name: pitest-report
          path: target/pit-reports/
      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin +refs/heads/gh-pages:refs/remotes/origin/gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          pr_id=${{ github.event.pull_request.number }}
          mkdir -p $pr_id
          cp -r target/pit-reports/* $pr_id/
          git add $pr_id
          git commit -m "Update mutation coverage report for PR #$pr_id"
          git push origin gh-pages
      - name: Post coverage report link
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Mutation Coverage Report**
            The mutation coverage report is available [here](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.event.pull_request.number }}/index.html).
          identifier: mutation-coverage-report